baseURL = 'https://www.sanderdorigo.nl/'
languageCode = 'nl-nl'
defaultContentLanguage = 'nl'
title = 'Sander Dorigo'
theme = "researcher"
rssLimit = 10

[taxonomies]
  category = 'categories'
  domain = "domains"
  2006 = "2006"
  2007 = "2007"
  2008 = "2008"
  2009 = "2009"
  2010 = "2010"
  2011 = "2011"
  2012 = "2012"
  2013 = "2013"
  2014 = "2014"
  2015 = "2015"
  2016 = "2016"
  2017 = "2017"
  2018 = "2018"
  2019 = "2019"
  2020 = "2020"
  2021 = "2021"
  2022 = "2022"

enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally

[params]
  lang='nl'
  content='NL'
  author = "Sander Dorigo"
  description = "Persoonlijke website van Sander Dorigo"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "© Sander Dorigo"
    url = "https://github.com/SDx3/sanderdorigo.nl"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/sanderdorigo"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/sanderdorigo/"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:mail@sanderdorigo.nl"

[permalinks]
  "/" = "/:filename"
  "blog" ="/:year/:month/:title/"
  "stream" ="/stream/:year/:month/:title/"

[menu]
  [[menu.main]]
    name = "Over"
    url = "/about"
    weight = 1
 [[menu.main]]
   name = "Stream"
   url = "/stream"
   weight = 2
 [[menu.main]]
   name = "Weblog"
   url = "/blog"
   weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
