name: Build website
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Upload
        uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          connection_string: ${{ secrets.AZURE_STORAGE_SAS }}
          source_dir: public
          extra_args: '--overwrite'
          container_name: $web
          sync: true
